# =======================================================
# ui.R — Dashboard Layout
# =======================================================
header <- dashboardHeader(title = "Reactome Pathway Dashboard")

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Monocyte Data", tabName = "dashboard", icon = icon("chart-bar")),
    menuItem("Reactome Pathways Distribution", tabName = "dashboard2", icon = icon("project-diagram")),
    menuItem("Pathway Intersections (UpSetR)", tabName = "dashboard3", icon = icon("layer-group"))
  )
)

# ---- Page 1 ----
frow1 <- fluidRow(
  tags$div(
    style = "padding:1em;",
    markdown("
### Background

We profiled **123,965** circulating monocytes via scRNA-seq in 32 individuals stratified by HIV and AS status. 

Each bar represents the total number of cell per monocyte sub-cluster.

### Notes
- Colors correspond to defined monocyte sub-cluster (CD14, CD14-active, CD16, Intermediate, PMC).
")
  ),
  box(
    title = "Number of Cell per Cluster",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    plotOutput("enrollement", height = "500px")
  )
)

# ---- Page 2 ----
frow2 <- fluidRow(
  tags$div(
    style = "padding:1em;",
    markdown("
### Background

This page summarized the number of DE pathways grouped by **disease** across different monocyte sub-clusters.

- Barplot represents the total DE pathways detected per disease condition in different monocyte sub-clusters.
- Sankey plot shows the Reactome pathway category.

### Notes
- Reactome pathway category were generated by BioBert LLM model.

")
  ),
  box(
    title = "Number of DE Pathways by Cluster",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    plotOutput("enrollement2", height = "400px"),
    width = 6
  ),
  box(
    title = "Reactome Pathway Sankey Network",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    sankeyNetworkOutput("sankey_diagram", height = "700px"),
    width = 6
  )
)

# ---- Page 3: UpSetR ----
frow3 <- fluidRow(
  tags$div(
    style = "padding:1em;",
    markdown("
### Background

This page showed DE pathways across all monocyte sub-clusters in HIV+, AS+, and HIV+AS+ vs. health control group.

Each bar represents the total pathways detected per disease condition, allowing comparison across  sub-clusters

### Notes
- **Signal Transduction, Immune System, Disease, Metabolism** category were selected only.
")
  ),
  box(
    title = "UpSetR Plot",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    plotOutput("upset_plot", height = "500px"),
    width = 12
  ),
  
  box(title = "Pathways in Selected Sub-cluster(s)",
      status = "primary",
      width = 12,  
      # --- Top summary line with two info boxes ---
      fluidRow(
        # summary count boxes
        valueBoxOutput("pathway_count_box", width = 6),
        valueBoxOutput("gene_count_box", width = 6)
      ),
      
      fluidRow(
        # detailed list boxes
        uiOutput("pathway_list_box", width = 6),
        uiOutput("gene_list_box", width = 6)
      )
  ),
      
  box(
    title = "Pathways in Selected Sub-cluster(s)",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    # horizontal layout for inputs
    fluidRow(
      column(
        width = 8,
        selectInput(
          "intersection_choice",
          "Select Sub-cluster(s):",
          choices = NULL,
          multiple = TRUE,
          width = "100%"
        )
      ),
      column(
        width = 4,
        selectInput(
          "n_rows",
          "Rows per page:",
          choices = c(50, 100, 200, 300, 400, 500),
          selected = 50,
          width = "100%"
        )
      )
    ),
    
    # data table output
    DTOutput("shared_Pathways")
  ),
  
  box(
    title = "Genes in Selected Pathway(s)",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    width = 6,

    DTOutput("gene_table")
  ),
    

  box(
    title = "Reactome Pathway–Gene Network",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    width = 12,
    

    visNetworkOutput("gene_vis", height = "700px")
  )
)


# ---- Body ----
body <- dashboardBody(
  tabItems(
    tabItem(tabName = "dashboard", frow1),
    tabItem(tabName = "dashboard2", frow2),
    tabItem(tabName = "dashboard3", frow3)
  )
)

ui <- dashboardPage(header, sidebar, body, skin = "purple")